baseURL = 'https://24x7fpga.com/'
languageCode = 'en-us'
title = 'Home'  # 'Think, Design and Build' change this if you use hello-friend-ng
theme = "hugo-PaperMod"


# # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
# For PaperMod 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #     
[params.profileMode]
    enabled     = true 
    imageUrl    = "/img/ai-zeus3.png"
    imageWidth  = 120 # custom size
    imageHeight = 240 # custom size
    title = "Think, Design and Build"
    

[params]
  showWordCount = true 
  author = "kiran"
  #title = "24x7fpga"
  description = "24x7fpga"
  defaultTheme = "light" 
  #DateFormat = "2006-01-02"
  ShowReadingTime= true
  #ShowShareButtons= true
  ShowPostNavLinks= false
  ShowBreadCrumbs= false
  ShowCodeCopyButtons= true
  disableSpecial1stPost= false
  disableScrollToTop= false
  comments= false
  hidemeta= false
  hideSummary= true
  showtoc= false
  tocopen= false
  enableEmoji = true
  
 
 [params.Singlefooter]
    path      = "/img/org_mode.png"
    alt      = "footer"
    maxWidth = "50px"                

  [[params.socialIcons]]
      name = "linkedin"
      url  = "https://www.linkedin.com/in/kiran760043/" 

  [[params.socialIcons]]
      name = "github"
      url  = "https://github.com/24x7fpga"
    
    [[params.socialIcons]]
      name = "googlescholar"
      url  = "https://googlescholar.com/"

    [[params.socialIcons]]
      name = "orcid"
      url  = "https://orcid.org/0009-0003-7024-3868"
    
    [[params.socialIcons]]
      name = "instagram"
      url  = "https://www.instagram.com/negativeparking/"



# # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
# General
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #  

  [submenu]

  [[submenu.main]]
    identifier = "try"
    name = "try"
    utl ="try/"

  [menu]
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/about"
    weight     = 10

  [[menu.main]]
    identifier = "research"
    name       = "research"
    url        = "research/2024_07_08_10_15_40_research"
    weight     = 20

  [[menu.main]]
    identifier = "rtl_directory"
    name       = "rtl directory"
    url        = "rtl_directory/2024_06_05_00_21_53_rtl_design_directory" 
    weight     = 30

    [[menu.main]]
    identifier = "sv_directory"
    name       = "sv directory"
    url        = "sv_directory/2024_06_27_16_53_00_sv_verification_directory" 
    weight     = 40

    [[menu.main]]
    identifier = "tags"
    #name       = "tags"
    pre        = "tags"
    #post       = "<i class='fas fa-tag' aria-hidden='true'></i>" #<i class='fas fa-tags fa-fw'></i>
    url        = "tags/" 
    weight     = 50





